// frontend/react-client/src/components/AnalysisPanel.tsx
import React, { useEffect, useState } from 'react';
import styles from './AnalysisPanel.module.css';
import { analyzeRest } from '../services/analysisService';
import { AnalysisResponse } from '../types/chess.types';

interface AnalysisPanelProps {
  fen: string;
  autoAnalyze?: boolean;
}

/**
 * Sidebar panel that shows Stockfish evaluation for the current position.
 */
const AnalysisPanel: React.FC<AnalysisPanelProps> = ({ fen, autoAnalyze = false }) => {
  const [depth, setDepth]     = useState(12);
  const [result, setResult]   = useState<AnalysisResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError]     = useState<string | null>(null);

  useEffect(() => {
    if (autoAnalyze && fen) analyze();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fen, autoAnalyze]);

  const analyze = async () => {
    if (!fen) return;
    setLoading(true);
    setError(null);
    try {
      const res = await analyzeRest({ fen, depth });
      setResult(res);
    } catch (err: unknown) {
      const message = (err as { response?: { data?: { detail?: string } } })
        ?.response?.data?.detail ?? 'Analysis failed';
      setError(message);
    } finally {
      setLoading(false);
    }
  };

  const formattedScore = (): string => {
    if (!result) return '–';
    if (result.isMate) {
      return result.mateIn > 0 ? `M${result.mateIn}` : `-M${Math.abs(result.mateIn)}`;
    }
    const pawns = (result.score / 100).toFixed(2);
    return result.score >= 0 ? `+${pawns}` : pawns;
  };

  return (
    <div className={styles.panel}>
      <h3>Engine Analysis</h3>

      <div className={styles.controls}>
        <label>
          Depth
          <input
            type="number"
            value={depth}
            min={1}
            max={30}
            onChange={e => setDepth(Number(e.target.value))}
          />
        </label>
        <button
          className={styles.primary}
          onClick={analyze}
          disabled={loading || !fen}
        >
          {loading ? 'Analysing…' : 'Analyse'}
        </button>
      </div>

      {error && <p className={styles.error}>{error}</p>}

      {result && (
        <div className={styles.result}>
          <div className={styles.row}>
            <span className={styles.label}>Evaluation</span>
            <span className={`${styles.score} ${result.score > 0 ? styles.positive : result.score < 0 ? styles.negative : ''}`}>
              {formattedScore()}
            </span>
          </div>
          <div className={styles.row}>
            <span className={styles.label}>Best Move</span>
            <span className={styles.bestMove}>{result.bestMove}</span>
          </div>
          <div className={styles.row}>
            <span className={styles.label}>Depth</span>
            <span>{result.depth}</span>
          </div>
          {result.topMoves.length > 0 && (
            <div className={styles.pv}>
              <span className={styles.label}>Principal Variation</span>
              <p className={styles.pvLine}>{result.topMoves[0].line.join(' ')}</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default AnalysisPanel;

// frontend/angular-client/src/app/components/analysis-panel/analysis-panel.component.ts
import { Component, Input, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subscription } from 'rxjs';
import { AnalysisService } from '../../services/analysis.service';
import { AnalysisResponse } from '../../models/analysis.model';

/**
 * Displays Stockfish evaluation and best-move suggestion for the current
 * board position. Supports both REST (on-demand) and WebSocket (live) modes.
 */
@Component({
  selector: 'app-analysis-panel',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './analysis-panel.component.html',
  styleUrls: ['./analysis-panel.component.css']
})
export class AnalysisPanelComponent implements OnChanges, OnDestroy {

  @Input() fen = '';
  @Input() autoAnalyze = false;

  depth = 12;
  result: AnalysisResponse | null = null;
  loading = false;
  error: string | null = null;

  private wsSub?: Subscription;

  constructor(private analysisService: AnalysisService) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['fen'] && this.autoAnalyze && this.fen) {
      this.analyze();
    }
  }

  analyze(): void {
    this.loading = true;
    this.error   = null;

    this.analysisService.analyzeRest({ fen: this.fen, depth: this.depth })
      .subscribe({
        next: res => {
          this.result  = res;
          this.loading = false;
        },
        error: err => {
          this.error   = err.error?.detail ?? 'Analysis failed';
          this.loading = false;
        }
      });
  }

  /** Formatted score string shown to the user. */
  get formattedScore(): string {
    if (!this.result) return '–';
    if (this.result.isMate) {
      return this.result.mateIn > 0
        ? `M${this.result.mateIn}`
        : `-M${Math.abs(this.result.mateIn)}`;
    }
    const pawns = (this.result.score / 100).toFixed(2);
    return this.result.score >= 0 ? `+${pawns}` : pawns;
  }

  ngOnDestroy(): void {
    this.wsSub?.unsubscribe();
  }
}

<div class="analysis-panel">
  <h3>Engine Analysis</h3>

  <div class="controls">
    <label>
      Depth
      <input type="number" [(ngModel)]="depth" min="1" max="30" />
    </label>
    <button class="primary" (click)="analyze()" [disabled]="loading || !fen">
      {{ loading ? 'Analysing…' : 'Analyse' }}
    </button>
  </div>

  <div *ngIf="error" class="error">{{ error }}</div>

  <div *ngIf="result" class="result">
    <div class="score-row">
      <span class="label">Evaluation</span>
      <span class="score" [class.positive]="result.score > 0" [class.negative]="result.score < 0">
        {{ formattedScore }}
      </span>
    </div>

    <div class="best-move-row">
      <span class="label">Best Move</span>
      <span class="best-move">{{ result.bestMove }}</span>
    </div>

    <div class="depth-row">
      <span class="label">Depth</span>
      <span>{{ result.depth }}</span>
    </div>

    <div *ngIf="result.topMoves.length > 0" class="pv-section">
      <span class="label">Principal Variation</span>
      <p class="pv-line">{{ result.topMoves[0].line.join(' ') }}</p>
    </div>
  </div>
</div>
