// frontend/angular-client/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ChessBoardComponent } from './components/chess-board/chess-board.component';
import { AnalysisPanelComponent } from './components/analysis-panel/analysis-panel.component';
import { GameService } from './services/game.service';
import { GameStatus } from './models/game.model';

/**
 * Root application component.
 * Orchestrates game creation, move submission, and analysis.
 */
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, ChessBoardComponent, AnalysisPanelComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'Chess App';

  gameId: string | null  = null;
  currentFen = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
  currentTurn: 'WHITE' | 'BLACK' = 'WHITE';
  gameStatus: GameStatus = 'IN_PROGRESS';
  moveHistory: string[]  = [];
  errorMessage: string | null = null;
  loading = false;
  boardDisabled = false;

  constructor(private gameService: GameService) {}

  ngOnInit(): void {
    this.newGame();
  }

  newGame(): void {
    this.loading = true;
    this.errorMessage = null;
    this.gameService.createGame().subscribe({
      next: res => {
        this.gameId       = res.gameId;
        this.currentFen   = res.fen;
        this.currentTurn  = res.turn;
        this.gameStatus   = res.status;
        this.moveHistory  = [];
        this.boardDisabled = false;
        this.loading      = false;
      },
      error: err => {
        this.errorMessage = 'Failed to create game: ' + (err.error?.detail ?? err.message);
        this.loading = false;
      }
    });
  }

  onMoveMade(uciMove: string): void {
    if (!this.gameId || this.gameStatus !== 'IN_PROGRESS') return;

    this.gameService.makeMove(this.gameId, uciMove).subscribe({
      next: res => {
        this.currentFen  = res.fen;
        this.currentTurn = res.turn;
        this.gameStatus  = res.status;
        this.moveHistory.push(uciMove);
        this.errorMessage = null;
        if (res.gameOver) {
          this.boardDisabled = true;
        }
      },
      error: err => {
        this.errorMessage = err.error?.detail ?? 'Illegal move';
      }
    });
  }

  get statusMessage(): string {
    switch (this.gameStatus) {
      case 'IN_PROGRESS': return `${this.currentTurn === 'WHITE' ? 'White' : 'Black'} to move`;
      case 'CHECKMATE':   return 'Checkmate!';
      case 'STALEMATE':   return 'Stalemate – Draw';
      default:            return this.gameStatus.replace(/_/g, ' ');
    }
  }
}

<div class="app-shell">
  <header class="app-header">
    <h1>♟ Chess App</h1>
    <div class="header-actions">
      <button class="primary" (click)="newGame()" [disabled]="loading">
        {{ loading ? 'Loading…' : 'New Game' }}
      </button>
    </div>
  </header>

  <main class="game-area">
    <!-- Board column -->
    <section class="board-section">
      <div class="status-bar" [class.game-over]="gameStatus !== 'IN_PROGRESS'">
        {{ statusMessage }}
      </div>

      <app-chess-board
        [fen]="currentFen"
        [playerColor]="'WHITE'"
        [disabled]="boardDisabled || gameStatus !== 'IN_PROGRESS'"
        (moveMade)="onMoveMade($event)"
      ></app-chess-board>

      <div *ngIf="errorMessage" class="error-banner">
        {{ errorMessage }}
      </div>
    </section>

    <!-- Side panel -->
    <aside class="side-panel">
      <!-- Move history -->
      <div class="move-history">
        <h3>Move History</h3>
        <ol class="move-list">
          <li *ngFor="let move of moveHistory; let i = index">
            <span class="move-number" *ngIf="i % 2 === 0">{{ (i / 2 | number:'1.0-0') + 1 }}.</span>
            {{ move }}
          </li>
        </ol>
      </div>

      <!-- Engine analysis -->
      <app-analysis-panel
        [fen]="currentFen"
        [autoAnalyze]="false"
      ></app-analysis-panel>
    </aside>
  </main>
</div>

// frontend/react-client/src/App.tsx
import React, { useCallback, useEffect, useState } from 'react';
import styles from './App.module.css';
import ChessBoard from './components/ChessBoard';
import AnalysisPanel from './components/AnalysisPanel';
import { createGame, makeMove } from './services/gameService';
import { GameStatus, MakeMoveResponse } from './types/chess.types';

const INITIAL_FEN = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';

/**
 * Root application component.
 * Manages game lifecycle and passes state down to child components.
 */
function App() {
  const [gameId, setGameId]           = useState<string | null>(null);
  const [fen, setFen]                 = useState(INITIAL_FEN);
  const [turn, setTurn]               = useState<'WHITE' | 'BLACK'>('WHITE');
  const [status, setStatus]           = useState<GameStatus>('IN_PROGRESS');
  const [moveHistory, setMoveHistory] = useState<string[]>([]);
  const [error, setError]             = useState<string | null>(null);
  const [loading, setLoading]         = useState(false);

  useEffect(() => { startNewGame(); }, []);

  const startNewGame = async () => {
    setLoading(true);
    setError(null);
    try {
      const game = await createGame();
      setGameId(game.gameId);
      setFen(game.fen);
      setTurn(game.turn);
      setStatus(game.status);
      setMoveHistory([]);
    } catch {
      setError('Failed to create game.');
    } finally {
      setLoading(false);
    }
  };

  const handleMove = useCallback(async (uciMove: string) => {
    if (!gameId || status !== 'IN_PROGRESS') return;
    setError(null);
    try {
      const res: MakeMoveResponse = await makeMove(gameId, uciMove);
      setFen(res.fen);
      setTurn(res.turn);
      setStatus(res.status);
      setMoveHistory(prev => [...prev, uciMove]);
    } catch (err: unknown) {
      const message = (err as { response?: { data?: { detail?: string } } })
        ?.response?.data?.detail ?? 'Illegal move';
      setError(message);
    }
  }, [gameId, status]);

  const statusMessage = (): string => {
    switch (status) {
      case 'IN_PROGRESS': return `${turn === 'WHITE' ? 'White' : 'Black'} to move`;
      case 'CHECKMATE':   return 'Checkmate!';
      case 'STALEMATE':   return 'Stalemate – Draw';
      default:            return status.replace(/_/g, ' ');
    }
  };

  return (
    <div className={styles.appShell}>
      <header className={styles.header}>
        <h1>♟ Chess App</h1>
        <button className={styles.primary} onClick={startNewGame} disabled={loading}>
          {loading ? 'Loading…' : 'New Game'}
        </button>
      </header>

      <main className={styles.gameArea}>
        <section className={styles.boardSection}>
          <div className={`${styles.statusBar} ${status !== 'IN_PROGRESS' ? styles.gameOver : ''}`}>
            {statusMessage()}
          </div>

          <ChessBoard
            fen={fen}
            disabled={status !== 'IN_PROGRESS'}
            onMove={handleMove}
          />

          {error && <div className={styles.errorBanner}>{error}</div>}
        </section>

        <aside className={styles.sidePanel}>
          <div className={styles.moveHistory}>
            <h3>Move History</h3>
            <ol className={styles.moveList}>
              {moveHistory.map((move, i) => (
                <li key={i}>
                  {i % 2 === 0 && <span className={styles.moveNum}>{Math.floor(i / 2) + 1}.</span>}
                  {move}
                </li>
              ))}
            </ol>
          </div>

          <AnalysisPanel fen={fen} autoAnalyze={false} />
        </aside>
      </main>
    </div>
  );
}

export default App;
